### ISSUE TITLE
Libraries that have single letter variables confict with Identifier name '*' is too short

### ISSUE THREAD

**Issue by martijnhartlief** [alexkramer98/eslint-config-evil-vue#1]
Libraries that have single letter variables confict with  Identifier name '*' is too short

For example RGB

```
35:25  error    Identifier name 'r' is too short (< 2)  id-length
36:25  error    Identifier name 'g' is too short (< 2)  id-length
37:25  error    Identifier name 'b' is too short (< 2)  id-length
```

or X, Y, Z dimensions

```
334:25  error    Identifier name 'x' is too short (< 2)                                                                       id-length
335:25  error    Identifier name 'y' is too short (< 2)                                                                       id-length
```

**Comment by alexkramer98** [comment]
If using these variable names yourself, I would suggest you substitute the name of the variable with something >= 2 chars. It is generally considered a bad practise to use single variable names, although I can understand where you are coming from.

However, if you have no control over these variable names - like third party libraries for instance - I would advise you to make a specific exception; you can exclude (specific) rules for the entire project, suppress them for a specific file or set of files, or suppress an error for a specific line in a file.

Please consult the [ESLint docs](https://eslint.org/docs/user-guide/configuring/rules) for how to do this.
